# Menggunakan image Python dasar
FROM python:3.9-slim

# Set direktori kerja di dalam container
WORKDIR /app

# Upgrade pip dan setuptools
RUN pip install --upgrade pip setuptools

# Menyalin file requirements.txt ke container
COPY requirements.txt /app/

# Install dependensi yang diperlukan
RUN pip install -r requirements.txt

# Menyalin semua file aplikasi ke dalam container
COPY . /app/

# Menjalankan aplikasi menggunakan gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]
