FROM python:3.9-slim

# Install dependencies
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy project files
COPY . /app/

# Set environment variable to make the app run
CMD ["python", "app.py"]  # Sesuaikan dengan file utama aplikasi Pythonmu (Flask atau Django)
